In [3]:
 # To predict the price of car based on given feature
import pandas as pd
import numpy as np
df=pd.read_csv('car data.csv')
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [7]:
df.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [11]:
df.describe(include='O')

       Car_Name Fuel_Type Seller_Type Transmission
count       301       301         301          301
unique       98         3           2            2
top        city    Petrol      Dealer       Manual
freq         26       239         195          261

In [13]:
df.drop('Car_Name',axis=1,inplace=True)

In [17]:
df['year']=2025-df.Year

In [25]:
df.Kms_Driven = np.log(df.Kms_Driven)

In [27]:
df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,year
0,2014,3.35,5.59,10.203592,Petrol,Dealer,Manual,0,11
1,2013,4.75,9.54,10.668955,Diesel,Dealer,Manual,0,12
2,2017,7.25,9.85,8.839277,Petrol,Dealer,Manual,0,8
3,2011,2.85,4.15,8.556414,Petrol,Dealer,Manual,0,14
4,2014,4.60,6.87,10.656082,Diesel,Dealer,Manual,0,11

In [31]:
df = pd.get_dummies(df, columns=['Fuel_Type','Seller_Type','Transmission'])

In [33]:
df

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,year,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,3.35,5.59,10.203592,0,11,False,False,True,True,False,False,True
1,2013,4.75,9.54,10.668955,0,12,False,True,False,True,False,False,True
2,2017,7.25,9.85,8.839277,0,8,False,False,True,True,False,False,True
3,2011,2.85,4.15,8.556414,0,14,False,False,True,True,False,False,True
4,2014,4.60,6.87,10.656082,0,11,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,10.433763,0,9,False,True,False,True,False,False,True
297,2015,4.00,5.90,11.002100,0,10,False,False,True,True,False,False,True
298,2009,3.35,11.00,11.384342,0,16,False,False,True,True,False,False,True
299,2017,11.50,12.50,9.104980,0,8,False,True,False,True,False,False,True
300,2016,5.30,5.90,8.605936,0,9,False,False,True,True,False,False,True

In [35]:
x = df[['Present_Price', 'Kms_Driven', 'Owner', 'Year', 'Fuel_Type_Diesel',
       'Fuel_Type_Petrol', 'Seller_Type_Individual', 'Transmission_Manual']]
y = df.Selling_Price

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [39]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)

In [41]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9110536114155718

In [48]:
#Randomized Search CV
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

In [49]:
# Random search of parameters, using 3 fold cross validation,
# search across 100 different combinations
rf_random = RandomizedSearchCV(estimator = regressor, param_distributions = random_grid,scoring='neg_mean_squared_error', n_iter = 10, cv = 3, verbose=1, random_state=42, n_jobs =-1)

In [50]:
rf_random.fit(x_train,y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'max_depth': [5, 10, 15, 20, 25, 30],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000, 1100,
                                                         1200]},
                   random_state=42, scoring='neg_mean_squared_error',
                   verbose=1)

In [54]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 25}

In [56]:
y_pred=rf_random.predict(x_test)
r2_score(y_test,y_pred)

0.8734207244816179

In [58]:
from sklearn.ensemble import RandomForestRegressor
regressor_model=RandomForestRegressor()
regressor_model.fit(x_train,y_train)
y_pred = regressor_model.predict(x_test)
r2_score(y_test,y_pred)

0.9143700381481914

In [62]:
import pickle
with open('model_RFR.pkl', 'wb') as f:
    pickle.dump(regressor_model, f)
    f.close

In [76]:
k = regressor_model([[23,45,1,3,0,1,1,1]])
print(k)

TypeError: 'RandomForestRegressor' object is not callable

In [72]:
k = regressor_model.predict([[23, 45, 1, 3, 0, 1, 1, 1]])
print(k)

[3.492]

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [78]:
#Using xgb regressor
import xgboost as xgb
model = xgb.XGBRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
r2

0.8951886969237397